# Generated by Django 5.1.2 on 2025-05-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityIssuedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('tx_hash', models.CharField(max_length=66)),
                ('ipfs_hash', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserUploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='user_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('tx_hash', models.CharField(blank=True, max_length=66, null=True)),
                ('ipfs_hash', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
