# Generated by Django 5.1.2 on 2025-05-25 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorityissueddocument',
            name='file',
        ),
        migrations.RemoveField(
            model_name='useruploadeddocument',
            name='file',
        ),
    ]
