# Generated by Django 5.1.2 on 2025-05-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_remove_authorityissueddocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityissueddocument',
            name='document_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useruploadeddocument',
            name='document_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
