# Generated by Django 5.1.2 on 2025-05-29 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_authorityissueddocument_document_index_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('document_index', models.IntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('verified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications_received', to=settings.AUTH_USER_MODEL)),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
