# Generated by Django 5.1.2 on 2025-05-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_verificationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationhistory',
            name='ipfs_hash',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
