# Generated by Django 5.1.2 on 2025-06-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_verificationhistory_ipfs_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityissueddocument',
            name='block_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='useruploadeddocument',
            name='block_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.DeleteModel(
            name='VerificationHistory',
        ),
    ]
