# Generated by Django 5.1.2 on 2025-06-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_authorityissueddocument_block_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorityissueddocument',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useruploadeddocument',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
