# Generated by Django 5.1.2 on 2025-06-01 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_authorityissueddocument_flagged_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorityissueddocument',
            old_name='block_hash',
            new_name='block_tx_hash',
        ),
        migrations.RenameField(
            model_name='useruploadeddocument',
            old_name='block_hash',
            new_name='block_tx_hash',
        ),
    ]
