# Generated by Django 5.1.2 on 2025-06-01 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_index', models.PositiveIntegerField()),
                ('flag_status', models.BooleanField(choices=[(True, 'Flagged'), (False, 'Unflagged')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_actions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(blank=True, max_length=100, null=True)),
                ('ipfs_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('document_index', models.IntegerField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('verified_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications_received', to=settings.AUTH_USER_MODEL)),
                ('verifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
