# Generated by Django 5.1.5 on 2025-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='authority_proofs/'),
        ),
    ]
