# Generated by Django 5.1.5 on 2025-08-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('REGISTER', 'Register'), ('UPLOAD_DOCUMENT', 'Upload Document'), ('ISSUE_DOCUMENT', 'Issue Document'), ('VERIFY_AUTHORITY', 'Verify Authority'), ('FLAG_DOCUMENT', 'Flag Document'), ('CREATE_USER', 'create user'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
